### Site Settings ###
title               : Ted's Portfolio
description         : >-
                      Computer Science student at William & Mary interested in software engineering and AI.
baseurl             : "/MyPortfolio"            # Change to empty quotes if you are hosting your site at <your-username>.github.io directly
repository          : tmtran03/MyPortfolio      # Change to <your-username>/<your-username>.github.io (or remove it if you don't need remote projects)
remote_theme        : yousinix/portfolYOU
open_new_tab        : false                    # Opens external URLs in new tab (works for posts, projects and navbar only)


### Plugins ###
plugins:
  - jemoji


### Navbar Settings ###
nav_exclude:                                            # The following paths are excluded from navbar
  - pages/tags.html
  - pages/404.html
  - pages/index.md


### Author Info ###
author:
  name              : Ted Tran
  image             : https://i.imgur.com/0mUNc3O.jpg   # replace later with your own photo if you want
  github            : tmtran03


### Posts ###
permalink: /blog/:title


### Collections ###
collections:
  projects:
    output: true
    permalink: /projects/:name



### Disqus ###
disqus:
  shortname:


### Analytics ###
analytics:
  enabled: false                                        # Set true to enable analytics
  google:
    tracking_id: your-google-tracking-id


### Buy me a coffee ###
# See https://www.buymeacoffee.com/
buymeacoffee:
  enabled: false
  username: your_username
  color: "#007bff"
  message: "Thank you for visiting."                    # Message to be displayed aside from the button for a few seconds.
  description: "Support me on Buy me a coffee!"


### Defaults for collections ###
defaults:
  - scope:
      path: ""
      type: "projects"
    values:
      layout: "page"
  - scope:
      path: ""
      type: "posts"
    values:
      comments: false                                   # Set to true to enable disqus comments


### Exclude from processing ###
exclude:
  - README.md
  - CONTRIBUTING.md
  - LICENSE
  - "*.log"
